#!/bin/bash

# Set codec options
if [ "$3" = opus ]; then
    export CODEC="opus -q 128"
elif [ "$3" = ogg ]; then
    export CODEC="ogg -q 6"
elif [ "$3" = mp3 ]; then
    export CODEC="mp3"
elif [ "$3" = flac ]; then
    export CODEC="flac"
else
    echo "Syntax: batchenc INPUTDIR OUTPUTDIR {opus,ogg,flac,mp3}"
    exit
fi
read -p "Source directory is \""$1"\". Is this correct? > " yn
case $yn in
    [Yy]* ) : ;;
    [Nn]* ) exit ;;
    * ) echo "Please answer yes or no.";;
esac

read -p "Target directory is \""$2"\". Is this correct? > " yn
case $yn in
    [Yy]* ) : ;;
    [Nn]* ) exit ;;
    * ) echo "Please answer yes or no.";;
esac


# create directory lists
cd "$1"
sourcedirs="$(find . -type d -name "*")"
cd "$2"
targetdirs="$(find . -type d -name "*")"

# clean up target directory
if [[ "$sourcedirs" == "$targetdirs" ]]; then
    echo "Nothing to do..."
    exit
fi

printf %s "$targetdirs" | while read -r line; do
    cd "$1"
    if [[ ! -d "${line}" ]]; then
        echo ""${line}" not in source tree, deleting..."
        cd "$2"
        rm -fr "${line}"
    fi
done


# create directory list
cd "$1"
sourcedirs="$(find . -type d -name "*" -print0 | while read -d $'\0' a; do echo "$a"; done)"

# check if target is missing directories
printf %s "$sourcedirs" | while read -r line; do
    cd $2
    if [[ ! -d "${line}" ]]; then
        echo "Transcoding "${line}""

        # transcode to CODEC
        caudec -O "${line}" -K -s -c $CODEC "$1""${line}"/*.flac
    fi
done
