#!/bin/bash

main () {
    #scp tauron:/home/carnager/.mpdscribble/mpd-formatted-tracks.txt /tmp/scrobbles > /dev/null
    stuff=$(grep -i "$name" /tmp/scrobbles |awk '{first = $1; $1 = ""; print $0 }' | sort | uniq -c)
    if [[ -n $album ]]; then
        if [[ -z $name ]]; then exit; fi
        rm -f /tmp/list
        echo "${stuff}" | sort | while read line; do
            plays=$(echo "$line" | awk -F ' ' '{ print $1 }')
            split=$(echo "$line" | awk '{first = $1; $1 = ""; print $0}' | cut -c 2-)
            artist=$(echo "$split" | awk -F ' - ' '{ print $1 }')
            title=$(echo "$split" | awk -F ' - ' '{ print $2 }')
            echo -e "${plays} $(mpc search --format '%artist% - %title% - %album%' artist "${artist}" title "${title}" | head -1)" >> /tmp/list
        done
        echo -e "Most track plays (albums) for artist \"${name}\":\n"   
        cat /tmp/list | awk -F ' - ' '{ print $1,"-",$3 }' | distribution -g --height=$lines --size=full --char=$char --width=100 ${color} 2>/dev/null | grep -vE "^-"
    else
        echo "${stuff}" | sort | distribution -g --height=$lines --size=full --char=$char --width=100 ${color} 2>/dev/null
    fi
}

printHelp () {
cat << EOF
local.fm
Usage: ${0##*/} [-sa] [-n KEYWORD] [-c CHARACTER] [-l LINES]

    -n "keyword"    keyword to search for (has to be first option)
    -s              colorize output
    -a              print album stats (needs "-n")
    -c "foo"        use character "foo" for histogram
    -l "int"        print "int" lines
EOF
}

OPTIND=1

# default options
char=ba
lines=10

# parse arguments
while getopts "hasn:l:c:" opt; do
    case "$opt" in
        h)
            printHelp
            exit 0
            ;;
        n)
            name=$OPTARG
            ;;
        a)
            if [[ -z $name ]]; then
                echo "No artist specified"
                exit 0
            else
                album=true
            fi
            ;;
        l)
            lines=$OPTARG
            ;;
        c)
            char=$OPTARG
            ;;
        s)
            color="--color"
            ;;
    esac
done
shift "$((OPTIND-1))"
main
