#!/bin/bash

main () {
    stuff=$(grep -i "$name" mpd-formatted-tracks.txt |awk '{first = $1; $1 = ""; print $0 }' | sort | uniq -c | sort)
    if [[ -n $album ]]; then
        if [[ -z $name ]]; then exit; fi
        rm -f /tmp/list
        echo "${stuff}" | sort | while read line; do
            plays=$(echo "$line" | awk -F ' ' '{ print $1 }')
            split=$(echo "$line" | awk '{first = $1; $1 = ""; print $0}' | cut -c 2-)
            artist=$(echo "$split" | awk -F ' - ' '{ print $1 }')
            title=$(echo "$split" | awk -F ' - ' '{ print $2 }')
            echo -e "${plays} $(mpc search --format '%artist% - %title% - %album%' artist "${artist}" title "${title}" | head -1)" >> /tmp/list
        done
        echo -e "Most track plays (albums) for artist \"${name}\":\n"   
        cat /tmp/list | awk -F ' - ' '{ print $1,"-",$3 }' | distribution -g --height=$lines --size=full --char=$char --width=100 ${color} 2>/dev/null | grep -vE "^-"
    else
        echo "${stuff}" | sort | distribution -g --height=$lines --size=full --char=$char --width=100 ${color} 2>/dev/null
    fi
}

printHelp () {
    echo -e "local.fm\n"
    echo "Usage:"
    echo -e "localfm \"ARTIST\" [--color, --album] [--char \"foo\", --lines \"int\"]\n"
    echo "--color          colorize output"
    echo "--album          print album stats"
    echo "--char \"foo\"     use character \"foo\" for histogram"
    echo "--lines \"int\"    print \"int\" lines"

    exit
}

if [[ $1 == "--help" || $1 == "-h" ]]; then
    printHelp
elif [[ -z $1 ]]; then
    if [[ $2 == "--album" || $3 == "--album" ]]; then
        echo "No artist supplied"
    else
        echo -e "Printing overall track stats\n"
    fi
    name=$1
else
    if [[ $3 == "--album" || $2 == "--album" ]]; then
        :
    else
        echo -e "Most played tracks by artist \"${name}\":\n"
    fi
    name="$1"
fi
if [[ $4 == "--lines" ]]; then
    lines=$5
else
    lines=10
fi
if [[ $6 == "--char" ]]; then
    char=$7
else
    char="ba"
fi
if [[ $2 == "--color" || $3 == "--color" ]]; then
    color="--color"
fi
if [[ $3 == "--album" || $2 == "--album" ]]; then
    album=true
fi
main
