#!/bin/bash
#script to list number of albums for each artist.
mpc list albumartist | grep -Ev 'Sampler|Soundtrack|Tribute|Various Artists' | while read line; do echo "$line" "$( mpc find albumartist "$line" | cut -d / -f 2-3 | uniq | wc -l )" ; done < <(mpc list albumartist) | awk '{print $NF,$0}' | sort -n | cut -f2- -d' ' | tac
