#!/bin/bash

FILE="$(pwd)/${1}"
ncat -l 8095 -c "echo -e \"HTTP/1.0 200 OK\r\nDate: $(date)\r\nServer: mpdserve/0.1\r\nConnection: close\r\nCache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0\r\nPragma: no-cache\r\nContent-Transfer-Encoding: binary\r\nContent-Length: $(wc -c < "$FILE")\r\nContent-Type: $(file -b --mime-type "$FILE")\r\n\r\n\r\n\";cat $(pwd)/\"${1}\";" &
mpc clear
mpc add "http://192.168.1.13:8095/${1}"
mpc play
pos=$(mpc current -f %position%)
wait
mpc del $pos
