#!/bin/sh
 #
 # mpdpl2html - MPD playlist to HTML
 # by pfish - 2010
 # Version 0.1
 # License: GPL 2
 #
 # Requirements:
 #       mpd
 #       mpc
 #       sed
 #
 
 #USER=`whoami`
 PLAYLIST=$(mpc playlist)
 FILE="mpdplaylist.html"
 DATE=$(date -R)
 
rm -f /tmp/mpd_playlist_tracks
echo "$PLAYLIST" | while read line; do
    artist=$(echo "$line"|awk -F ' - ' '{ print $1 }')
    title=$(echo "$line"|awk -F ' - ' '{ print $2 }')
    echo "<tr class=\"newartist\"><td rowspan=\"1\">${artist}</td>" >> /tmp/mpd_playlist_tracks
    echo "<td>${title}</td></tr>" >> /tmp/mpd_playlist_tracks
done


 echo "<!-- Generated with mpdpl2html by pfish - $DATE -->
 <html>
<head>
<meta charset=\"utf-8\"/>
<link rel=\"stylesheet\" href=\"http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css\">
<style>
        body{background:#eee}
        table{
        margin:5em auto;
        max-width:56em;
        background: white;
        }
</style>
<link href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\">
</head>
<body>
<div class=\"table-responsive\">

<table id=\"music\" style=\"white-space: nowrap;\" class=\"table table-bordered\">
<thead>
<tr>
<th>Artist</th>
<th>Title</th>
</tr>
</thead>
<tbody>

 $(cat /tmp/mpd_playlist_tracks)
 <hr />
 </body>
 </html>" > $FILE
