#!/bin/bash
shopt -s nullglob globstar

root="$1"
basedir=~/.password-store/

list_passwords() {
	passwords=( ~/.password-store/**/*.gpg )

	for password in "${passwords[@]}"; do
		filename="${password#$basedir}"
		filename="${filename%.gpg}"
		echo "$filename"
	done
}

xdotool_type() {
	for (( i=0; i<${#1}; i++ )); do
		xdotool type "${1:$i:1}"
	done
}

mainMenu () {
	selected_password="$(list_passwords 2>/dev/null| rofi -dmenu)"
	rofi_exit=$?
	case ${rofi_exit} in
		0)
			true
			;;
		10)
			true
			;;
		*)
			exit ${rofi_exit}
			;;
	esac

	# clear stdin
	while read -e -t 0.1; do true; done

	password_temp=$(pass "$selected_password")
	password=$(echo "${password_temp}" | head -1)
	declare -A stuff

	# while IFS=':' read -r index value; do
		# stuff["${index}"]=${value}
	# done < <(pass "$selected_password" | tail -n+2 | grep ": ")

	while read LINE; do
		arrSplit=(${LINE//: / })
		stuff["${arrSplit[0]}"]=${arrSplit[1]}
	done < <(pass "${selected_password}" | tail -n+2 | grep ': ')

	if [[ $1 == "password" ]]; then
		xdotool_type "$password"

		# cleanup (for the paranoid)
		password=''
		selected_password=''
		password_temp=''
		for i in "${!stuff[@]}"; do
			stuff[$i]=''
			unset stuff[$i]
		done
		unset stuff
		unset password
		unset selected_password
		unset password_temp
		unset stuff

		exit 0
	fi

	if [[ $(echo "${password_temp}" | tail -1) == "NOTAB" ]]; then
		for i in "${!stuff[@]}"; do
			xdotool_type "${stuff[$i]}"
		done
		xdotool_type "$password"

		# cleanup (for the paranoid)
		password=''
		selected_password=''
		password_temp=''
		for i in "${!stuff[@]}"; do
			stuff[$i]=''
			unset stuff[$i]
		done
		unset stuff
		unset password
		unset selected_password
		unset password_temp
		unset stuff
	else
		for i in "${!stuff[@]}"; do
			xdotool_type "${stuff[$i]}"
			xdotool key Tab
		done
		xdotool_type "$password"

		# cleanup (for the paranoid)
		password=''
		selected_password=''
		password_temp=''
		for i in "${!stuff[@]}"; do
			stuff[$i]=''
			unset stuff[$i]
		done
		unset stuff
		unset password
		unset selected_password
		unset password_temp
		unset stuff
	fi
}

insertPass () {
	domain=$(echo "$1" | sed -e 's|^[^/]*//||' -e 's|/.*$||')
	pass=$(echo -e "Password for site $domain" | rofi -dmenu -p "Enter Password > ")
	user=$(echo -e "Username for site $domain" | rofi -dmenu -p "Enter User > ")
	notab=$(echo -e "Yes\nNo" | rofi -dmenu -p "Page uses Auto Tab? > ")

	cd "$HOME"/.password-store/"${root}"
	group=$(find . -maxdepth 1 -type d -not -name '.' -not -name '.git' | sed 's/^.\///g' | rofi -dmenu -p "Choose Group")

	if [[ "$notab" == "No" ]]; then
		pass insert -m -f "${root}"/"$group"/"$domain" < <(echo -e "${pass}\nUser: ${user}\n${domain}")
	elif [[ "$notab" == "Yes" ]]; then
		pass insert -m -f "${root}"/"$group"/"$domain" < <(echo -e "${pass}\nUser: ${user}\n${domain}\nNOTAB")
	fi
}

if [[ "$2" == "insert" ]]; then
	insertPass "$3"
elif [[ "$2"  == "type_password" ]]; then
	mainMenu password
else
	mainMenu
fi

